[package]
name = "async_job_examples"
version = "1.50.14"
authors = ["j-mendez <jeff@a11ywatch.com>"]
description = "Async job trait for Rust."
repository = "https://github.com/spider-rs/spider"
readme = "README.md"
keywords = ["async_job", "cron", "async_task"]
categories = ["web-programming"]
license = "MIT"
documentation = "https://docs.rs/async_job"
publish = false
edition = "2018"

[badges]
maintenance = { status = "as-is" }

[dev-dependencies]
tokio = { version = "^1.34.0", features = [ "rt-multi-thread", "macros", "time", "parking_lot" ] }

[dependencies.async_job]
version = "0.0.1"
path = "../async_job"
features = []

[[example]]
name = "example"
path = "example.rs"
